[2021-07-28 12:21:32,113] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 12:21:55,501] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\admin.py changed, reloading.
[2021-07-28 12:21:57,540] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 12:22:06,131] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 12:22:43,692] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\tasks\admin.py changed, reloading.
[2021-07-28 12:22:45,729] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 12:22:50,409] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23136
[2021-07-28 12:22:50,978] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 12:22:50,979] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 12:23:05,898] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/tasks/task/ HTTP/1.1" 200 58991
[2021-07-28 12:23:06,086] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 12:23:06,194] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/img/sorting-icons.svg HTTP/1.1" 200 1097
[2021-07-28 12:23:06,244] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[2021-07-28 12:23:11,112] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 60441
[2021-07-28 12:23:11,267] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 12:23:20,733] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/?Stars__exact=%E6%99%AE%E9%80%9A%E5%8F%B7&Status__exact=%E5%8F%AF%E9%80%89 HTTP/1.1" 200 64202
[2021-07-28 12:23:20,886] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 12:23:22,378] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/export/?Stars__exact=%E6%99%AE%E9%80%9A%E5%8F%B7&Status__exact=%E5%8F%AF%E9%80%89 HTTP/1.1" 200 5838
[2021-07-28 12:23:28,830] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/Miracle/miraclenumber/export/?Stars__exact=%E6%99%AE%E9%80%9A%E5%8F%B7&Status__exact=%E5%8F%AF%E9%80%89 HTTP/1.1" 200 7316
[2021-07-28 12:32:47,572] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\tasks\admin.py changed, reloading.
[2021-07-28 12:32:49,869] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 12:46:03,505] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23139
[2021-07-28 12:46:04,012] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/tasks/task/ HTTP/1.1" 200 58910
[2021-07-28 12:46:04,180] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 12:46:07,051] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 60441
[2021-07-28 12:46:07,206] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 13:05:30,289] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\tasks\admin.py changed, reloading.
[2021-07-28 13:05:32,338] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 13:05:36,697] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23118
[2021-07-28 13:05:37,184] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 60441
[2021-07-28 13:05:37,336] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 13:05:41,165] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/tasks/task/ HTTP/1.1" 200 60787
[2021-07-28 13:05:41,309] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 13:05:53,965] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/tasks/task/ajax HTTP/1.1" 200 62
[2021-07-28 13:05:55,454] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/tasks/task/ HTTP/1.1" 200 60787
[2021-07-28 13:05:55,606] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 13:48:23,721] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\admin.py changed, reloading.
[2021-07-28 13:48:25,707] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 13:48:35,995] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23118
[2021-07-28 13:48:36,486] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 62357
[2021-07-28 13:48:36,646] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 13:48:54,232] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/Miracle/miraclenumber/ajax HTTP/1.1" 200 62
[2021-07-28 13:48:55,571] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 62590
[2021-07-28 13:48:55,708] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 13:49:05,326] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/Miracle/miraclenumber/ajax HTTP/1.1" 200 62
[2021-07-28 13:49:06,631] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 62357
[2021-07-28 13:49:06,786] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 13:49:18,978] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\admin.py changed, reloading.
[2021-07-28 13:49:20,891] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 13:49:29,081] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23118
[2021-07-28 13:49:29,536] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 62363
[2021-07-28 13:49:29,687] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 13:49:42,769] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/Miracle/miraclenumber/ajax HTTP/1.1" 200 62
[2021-07-28 13:49:44,097] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 62596
[2021-07-28 13:49:44,254] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 13:50:01,248] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/Miracle/miraclenumber/ajax HTTP/1.1" 200 62
[2021-07-28 13:50:02,550] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 62662
[2021-07-28 13:50:02,720] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 13:50:09,928] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/Miracle/miraclenumber/ajax HTTP/1.1" 200 62
[2021-07-28 13:50:11,309] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 62363
[2021-07-28 13:50:11,448] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 14:29:51,856] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\urls.py changed, reloading.
[2021-07-28 14:29:53,904] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 14:30:01,714] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:01,714] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:02,217] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:02,217] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:02,815] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:02,815] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:03,429] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:03,430] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:04,044] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:04,045] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:04,647] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:04,647] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:05,250] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:05,251] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:05,865] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:05,866] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:07,577] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:07,579] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:08,191] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:08,192] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:08,797] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:08,797] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:09,397] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:09,397] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:09,998] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:09,998] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:10,597] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:10,598] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:11,213] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:11,214] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:11,829] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:11,830] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:12,447] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:12,447] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:13,064] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:13,065] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:18,814] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 14:30:24,901] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:30:24,902] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:30:29,084] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 14:30:31,600] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 62363
[2021-07-28 14:30:31,616] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/base.css?_=2.7 HTTP/1.1" 304 0
[2021-07-28 14:30:31,631] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/changelists.css?_=20180905 HTTP/1.1" 304 0
[2021-07-28 14:30:31,638] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 304 0
[2021-07-28 14:30:31,638] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/jquery.init.js HTTP/1.1" 304 0
[2021-07-28 14:30:31,641] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/responsive.css?_=20180905 HTTP/1.1" 304 0
[2021-07-28 14:30:31,641] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/core.js HTTP/1.1" 304 0
[2021-07-28 14:30:31,642] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 304 0
[2021-07-28 14:30:31,645] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/actions.js HTTP/1.1" 304 0
[2021-07-28 14:30:31,688] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/urlify.js HTTP/1.1" 304 0
[2021-07-28 14:30:31,688] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/prepopulate.js HTTP/1.1" 304 0
[2021-07-28 14:30:31,689] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 304 0
[2021-07-28 14:30:31,690] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/js/vendor/jquery/jquery.min.js HTTP/1.1" 304 0
[2021-07-28 14:30:31,695] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/css/fonts.css HTTP/1.1" 304 0
[2021-07-28 14:30:31,768] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 14:30:31,886] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 304 0
[2021-07-28 14:30:31,932] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 304 0
[2021-07-28 14:30:33,229] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/tasks/task/ HTTP/1.1" 200 60909
[2021-07-28 14:30:33,377] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 14:31:16,410] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\urls.py changed, reloading.
[2021-07-28 14:31:18,385] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 14:31:22,665] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:22,665] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:23,258] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:23,259] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:23,864] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:23,864] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:24,482] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:24,482] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:24,967] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET / HTTP/1.1" 200 5687
[2021-07-28 14:31:25,027] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[2021-07-28 14:31:25,040] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[2021-07-28 14:31:25,040] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1152
[2021-07-28 14:31:25,045] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[2021-07-28 14:31:25,072] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[2021-07-28 14:31:25,080] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[2021-07-28 14:31:25,091] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[2021-07-28 14:31:25,097] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[2021-07-28 14:31:25,111] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
[2021-07-28 14:31:25,147] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[2021-07-28 14:31:25,164] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/rest_framework/js/jquery-3.5.1.min.js HTTP/1.1" 200 89476
[2021-07-28 14:31:30,396] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:30,397] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:30,996] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:30,997] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:31,598] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:31,598] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:31,916] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm HTTP/1.1" 301 0
[2021-07-28 14:31:32,389] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/ HTTP/1.1" 200 8172
[2021-07-28 14:31:36,123] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:36,125] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:36,732] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:36,732] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:37,347] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:37,348] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:37,963] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:37,964] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:38,580] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:38,581] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:39,196] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:39,197] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:39,798] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:31:39,798] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:31:40,180] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 52, in NumberReport
    bar = Bar().add_xaxis(MiracleNumber.OPERATORS.values).set_global_opts(
AttributeError: 'tuple' object has no attribute 'values'
[2021-07-28 14:31:40,182] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberReport/ HTTP/1.1" 500 69123
[2021-07-28 14:33:14,927] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 14:33:16,889] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 14:33:22,787] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 63, in NumberReport
    return HttpResponse(c.render_embed())
  File "D:\Python39\lib\site-packages\pyecharts\charts\base.py", line 73, in render_embed
    self._prepare_render()
  File "D:\Python39\lib\site-packages\pyecharts\charts\base.py", line 88, in _prepare_render
    self.json_contents = self.dump_options()
  File "D:\Python39\lib\site-packages\pyecharts\charts\base.py", line 49, in dump_options
    json.dumps(self.get_options(), indent=4, default=default, ignore_nan=True)
  File "D:\Python39\lib\site-packages\simplejson\__init__.py", line 398, in dumps
    return cls(
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 298, in encode
    chunks = list(chunks)
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 696, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 652, in _iterencode_dict
    for chunk in chunks:
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 531, in _iterencode_list
    for chunk in chunks:
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 652, in _iterencode_dict
    for chunk in chunks:
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 607, in _iterencode_dict
    key = _stringify_key(key)
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 567, in _stringify_key
    raise TypeError('keys must be str, int, float, bool or None, '
TypeError: keys must be str, int, float, bool or None, not tuple
[2021-07-28 14:33:22,791] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberReport/ HTTP/1.1" 500 212803
[2021-07-28 14:35:10,876] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 14:35:12,815] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 14:35:35,556] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 14:35:37,449] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 14:35:42,751] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 63, in NumberReport
    return HttpResponse(c.render_embed())
  File "D:\Python39\lib\site-packages\pyecharts\charts\base.py", line 73, in render_embed
    self._prepare_render()
  File "D:\Python39\lib\site-packages\pyecharts\charts\base.py", line 88, in _prepare_render
    self.json_contents = self.dump_options()
  File "D:\Python39\lib\site-packages\pyecharts\charts\base.py", line 49, in dump_options
    json.dumps(self.get_options(), indent=4, default=default, ignore_nan=True)
  File "D:\Python39\lib\site-packages\simplejson\__init__.py", line 398, in dumps
    return cls(
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 298, in encode
    chunks = list(chunks)
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 696, in _iterencode
    for chunk in _iterencode_dict(o, _current_indent_level):
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 652, in _iterencode_dict
    for chunk in chunks:
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 531, in _iterencode_list
    for chunk in chunks:
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 652, in _iterencode_dict
    for chunk in chunks:
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 607, in _iterencode_dict
    key = _stringify_key(key)
  File "D:\Python39\lib\site-packages\simplejson\encoder.py", line 567, in _stringify_key
    raise TypeError('keys must be str, int, float, bool or None, '
TypeError: keys must be str, int, float, bool or None, not tuple
[2021-07-28 14:35:42,754] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberReport/ HTTP/1.1" 500 214439
[2021-07-28 14:36:46,515] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 14:36:48,378] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 14:37:45,494] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 17742)

[2021-07-28 14:38:00,019] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 17743)

[2021-07-28 14:38:06,565] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 88397
[2021-07-28 14:42:25,973] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 14:42:27,876] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 14:42:30,028] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 7150
[2021-07-28 14:43:06,619] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 14:43:08,742] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 14:43:13,052] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 7150
[2021-07-28 14:43:47,402] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 14:43:49,537] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 14:43:53,558] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 14:43:55,428] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 14:44:11,474] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 7150
[2021-07-28 14:44:32,598] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 14:44:34,579] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 14:44:41,459] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 5957
[2021-07-28 14:47:14,602] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\admin.py changed, reloading.
[2021-07-28 14:47:16,557] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 14:47:29,480] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:47:29,481] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:47:30,069] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:47:30,069] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:47:30,670] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:47:30,671] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:47:31,270] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:47:31,270] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:47:31,884] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:47:31,885] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:47:32,498] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:47:32,499] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:47:33,102] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:47:33,102] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:47:33,702] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:47:33,702] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:47:34,304] [log.py:224] [log:log_response] [WARNING]- Not Found: /favicon.ico
[2021-07-28 14:47:34,304] [basehttp.py:161] [basehttp:log_message] [WARNING]- "GET /favicon.ico HTTP/1.1" 404 5394
[2021-07-28 14:47:34,393] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin HTTP/1.1" 301 0
[2021-07-28 14:47:34,849] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 14:47:38,200] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 63647
[2021-07-28 14:47:38,353] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 14:47:40,976] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 5957
[2021-07-28 14:48:52,252] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miracleorders/ HTTP/1.1" 200 49907
[2021-07-28 14:48:52,404] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 14:48:56,160] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 5957
[2021-07-28 14:49:58,006] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 5957
[2021-07-28 14:50:31,268] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 5957
[2021-07-28 14:52:41,458] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 414648
[2021-07-28 14:52:41,472] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /static/js/call.js HTTP/1.1" 304 0
[2021-07-28 14:52:41,620] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 14:52:43,801] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/organization/ HTTP/1.1" 200 104844
[2021-07-28 14:52:43,960] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 14:52:45,504] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacts/ HTTP/1.1" 200 59453
[2021-07-28 14:52:45,690] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 14:52:47,492] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacthistory/ HTTP/1.1" 200 55547
[2021-07-28 14:52:47,635] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 14:52:51,457] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 63805
[2021-07-28 14:52:51,607] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 14:52:57,479] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 5957
[2021-07-28 14:53:41,838] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/tasks/task/ HTTP/1.1" 200 61037
[2021-07-28 14:53:42,004] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 14:59:12,520] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 14:59:12,969] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/tasks/task/ HTTP/1.1" 200 61133
[2021-07-28 14:59:13,126] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 14:59:17,633] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 63805
[2021-07-28 14:59:17,770] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:01:28,378] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:01:30,311] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:02:01,457] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:02:03,437] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:04:43,245] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:04:45,088] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:05:05,512] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\urls.py changed, reloading.
[2021-07-28 15:05:07,380] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:06:11,290] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\admin.py changed, reloading.
[2021-07-28 15:06:13,163] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:06:16,478] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\admin.py changed, reloading.
[2021-07-28 15:06:18,493] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:06:21,299] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:06:21,993] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 63829
[2021-07-28 15:06:22,136] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:06:40,555] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\Miracle\admin.py changed, reloading.
[2021-07-28 15:06:42,468] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:06:43,643] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:06:44,148] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65249
[2021-07-28 15:06:44,317] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:06:46,869] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 5957
[2021-07-28 15:06:51,000] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 5957
[2021-07-28 15:07:22,407] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\urls.py changed, reloading.
[2021-07-28 15:07:24,401] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:07:28,450] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:07:31,580] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65249
[2021-07-28 15:07:31,739] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:07:33,491] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 82, in NumberOrganizeReport
    ORG = MiracleNumber.Objects.all.distinct('Organize')
AttributeError: type object 'MiracleNumber' has no attribute 'Objects'
[2021-07-28 15:07:33,493] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 69270
[2021-07-28 15:08:13,960] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:08:15,962] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:08:17,712] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:08:20,151] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65249
[2021-07-28 15:08:20,297] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:08:21,917] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 82, in NumberOrganizeReport
    ORG = MiracleNumber.Objects.distinct('Organize')
AttributeError: type object 'MiracleNumber' has no attribute 'Objects'
[2021-07-28 15:08:21,919] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 69262
[2021-07-28 15:09:42,387] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:09:44,417] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:09:45,731] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:09:48,668] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65249
[2021-07-28 15:09:48,820] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:09:50,157] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 82, in NumberOrganizeReport
    ORG = MiracleNumber.Objects.values('Organize').distinct()
AttributeError: type object 'MiracleNumber' has no attribute 'Objects'
[2021-07-28 15:09:50,159] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 69280
[2021-07-28 15:10:22,344] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:10:24,340] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:10:31,062] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:10:39,635] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65249
[2021-07-28 15:10:39,784] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:10:41,203] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 87, in NumberOrganizeReport
    for y in ORG.values:
TypeError: 'method' object is not iterable
[2021-07-28 15:10:41,204] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 69935
[2021-07-28 15:11:37,206] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:11:39,293] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:11:42,461] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:11:44,234] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65249
[2021-07-28 15:11:44,376] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:11:45,736] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 85, in NumberOrganizeReport
    bar = Bar().add_xaxis(ORG.values).set_global_opts(
AttributeError: 'function' object has no attribute 'values'
[2021-07-28 15:11:45,738] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70013
[2021-07-28 15:12:25,581] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:12:27,469] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:12:52,418] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:12:54,408] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:13:00,623] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:13:02,522] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65249
[2021-07-28 15:13:02,682] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:13:04,241] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 88, in NumberOrganizeReport
    for y in ORG.values:
TypeError: 'method' object is not iterable
[2021-07-28 15:13:04,243] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 69961
[2021-07-28 15:13:22,349] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:13:24,359] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:13:37,827] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:13:39,854] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65249
[2021-07-28 15:13:40,031] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:13:41,260] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 88, in NumberOrganizeReport
    for y in ORG.values:
TypeError: 'method' object is not iterable
[2021-07-28 15:13:41,261] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 69949
[2021-07-28 15:14:19,201] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:14:21,033] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:14:48,511] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:14:50,463] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:14:56,275] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:14:58,139] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65490
[2021-07-28 15:14:58,303] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:15:01,318] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 5160
[2021-07-28 15:15:35,651] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:15:37,669] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:15:38,890] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:15:40,843] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65490
[2021-07-28 15:15:40,994] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:15:44,584] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 5160
[2021-07-28 15:16:02,047] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:16:04,010] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:16:07,807] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:16:10,123] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65490
[2021-07-28 15:16:10,291] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:16:13,706] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 5160
[2021-07-28 15:16:39,494] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:16:41,389] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:16:42,488] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:16:44,317] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65490
[2021-07-28 15:16:44,451] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:16:47,361] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 5160
[2021-07-28 15:16:58,528] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:17:00,411] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:17:02,289] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:17:04,042] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65490
[2021-07-28 15:17:04,221] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:17:06,996] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 5160
[2021-07-28 15:17:32,011] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:17:33,967] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:17:42,133] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:17:44,039] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:17:46,670] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 20712)

[2021-07-28 15:17:47,387] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 20710)

[2021-07-28 15:17:48,213] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 20716)

[2021-07-28 15:17:49,437] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 5160
[2021-07-28 15:17:55,710] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65490
[2021-07-28 15:17:55,867] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:17:58,902] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 5160
[2021-07-28 15:18:25,926] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:18:27,922] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:18:29,089] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:18:30,874] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65490
[2021-07-28 15:18:31,014] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:18:33,824] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 5164
[2021-07-28 15:23:21,217] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:23:23,690] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:23:24,847] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:23:26,581] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65490
[2021-07-28 15:23:26,719] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:23:29,769] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 92, in NumberOrganizeReport
    bar = bar.add_yaxis(y, y1)
  File "D:\Python39\lib\site-packages\pyecharts\charts\basic_charts\bar.py", line 50, in add_yaxis
    self._append_legend(series_name, is_selected)
  File "D:\Python39\lib\site-packages\pyecharts\charts\chart.py", line 89, in _append_legend
    self.options.get("legend")[0].get("selected").update({name: is_selected})
TypeError: unhashable type: 'dict'
[2021-07-28 15:23:29,771] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 84099
[2021-07-28 15:24:04,884] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:24:06,903] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:24:08,188] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:24:11,001] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65490
[2021-07-28 15:24:11,149] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:24:12,810] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 92, in NumberOrganizeReport
    bar = bar.add_yaxis(y, y1)
  File "D:\Python39\lib\site-packages\pyecharts\charts\basic_charts\bar.py", line 50, in add_yaxis
    self._append_legend(series_name, is_selected)
  File "D:\Python39\lib\site-packages\pyecharts\charts\chart.py", line 89, in _append_legend
    self.options.get("legend")[0].get("selected").update({name: is_selected})
TypeError: unhashable type: 'dict'
[2021-07-28 15:24:12,813] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 83753
[2021-07-28 15:24:31,821] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:24:33,770] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:24:36,583] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:24:38,369] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65490
[2021-07-28 15:24:38,524] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:24:41,653] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 85311
[2021-07-28 15:26:37,269] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:26:39,177] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:26:44,240] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:26:46,159] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65490
[2021-07-28 15:26:46,312] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:26:47,621] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 84, in NumberOrganizeReport
    bar = Bar().add_xaxis(ORG['organize']).set_global_opts(
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 290, in __getitem__
    raise TypeError(
TypeError: QuerySet indices must be integers or slices, not str.
[2021-07-28 15:26:47,624] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 75745
[2021-07-28 15:27:08,080] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:27:09,962] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:28:48,483] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:28:50,867] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:28:54,475] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:28:56,290] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65490
[2021-07-28 15:28:56,443] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:28:59,839] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8189
[2021-07-28 15:32:05,624] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/?q=%E9%9A%90%E6%9C%A8 HTTP/1.1" 200 51909
[2021-07-28 15:32:05,776] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:32:20,254] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/Miracle/miraclenumber/ajax HTTP/1.1" 200 62
[2021-07-28 15:32:21,574] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/?q=%E9%9A%90%E6%9C%A8 HTTP/1.1" 200 51762
[2021-07-28 15:32:21,728] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:32:30,096] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:32:31,794] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65335
[2021-07-28 15:32:31,940] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:32:35,842] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8124
[2021-07-28 15:32:53,793] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/?q=%E5%90%8C%E4%BB%81%E5%A0%82 HTTP/1.1" 200 55343
[2021-07-28 15:32:53,951] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:38:09,835] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8124
[2021-07-28 15:38:15,068] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 22336)

[2021-07-28 15:38:16,715] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 22348)

[2021-07-28 15:38:18,303] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 22351)

[2021-07-28 15:38:19,784] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 22356)

[2021-07-28 15:38:21,298] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 22360)

[2021-07-28 15:38:22,963] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 22364)

[2021-07-28 15:38:24,700] [basehttp.py:75] [basehttp:handle_error] [INFO]- - Broken pipe from ('127.0.0.1', 22367)

[2021-07-28 15:42:35,599] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:42:37,536] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:42:46,839] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:42:48,887] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:43:03,020] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:43:04,999] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:43:47,463] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:43:49,369] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:44:14,359] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:44:16,220] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:44:23,675] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8290
[2021-07-28 15:45:10,096] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:45:12,168] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:45:22,848] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:45:24,775] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:45:25,897] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:45:28,073] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65335
[2021-07-28 15:45:28,232] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 15:45:30,699] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8290
[2021-07-28 15:51:25,194] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:51:27,103] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:51:45,193] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:51:47,050] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:51:54,248] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:51:56,215] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:52:04,443] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:52:06,365] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:52:18,362] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:52:20,310] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:52:23,773] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:52:25,758] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:52:36,650] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 86, in NumberOrganizeReport
    x1.append(x['Organize'])
TypeError: 'MiracleNumber' object is not subscriptable
[2021-07-28 15:52:36,653] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70798
[2021-07-28 15:52:38,644] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 86, in NumberOrganizeReport
    x1.append(x['Organize'])
TypeError: 'MiracleNumber' object is not subscriptable
[2021-07-28 15:52:38,646] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70798
[2021-07-28 15:54:33,647] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 15:54:35,622] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 15:54:36,981] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 15:54:38,744] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65335
[2021-07-28 15:54:38,899] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:01:57,338] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 83, in NumberOrganizeReport
    print(ORG.Org_num)
AttributeError: 'QuerySet' object has no attribute 'Org_num'
[2021-07-28 16:01:57,340] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70506
[2021-07-28 16:02:46,404] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:02:48,697] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:02:50,046] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:02:52,170] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65335
[2021-07-28 16:02:52,338] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:02:53,918] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 83, in NumberOrganizeReport
    print(ORG['Organize'])
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 290, in __getitem__
    raise TypeError(
TypeError: QuerySet indices must be integers or slices, not str.
[2021-07-28 16:02:53,920] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 75359
[2021-07-28 16:04:03,473] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:04:05,638] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:04:10,044] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:04:11,926] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65335
[2021-07-28 16:04:12,088] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:04:13,425] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 86, in NumberOrganizeReport
    x1.append(x['Organize'])
TypeError: 'MiracleNumber' object is not subscriptable
[2021-07-28 16:04:13,427] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70799
[2021-07-28 16:04:38,298] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:04:40,469] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:04:43,826] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:04:45,668] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65335
[2021-07-28 16:04:45,823] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:04:47,263] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 86, in NumberOrganizeReport
    x1.append(x['Organize'])
TypeError: 'MiracleNumber' object is not subscriptable
[2021-07-28 16:04:47,265] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70708
[2021-07-28 16:05:15,169] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:05:17,154] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:05:18,323] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:05:24,816] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65335
[2021-07-28 16:05:24,985] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:05:26,466] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 86, in NumberOrganizeReport
    x1.append(x['Organize'])
TypeError: 'MiracleNumber' object is not subscriptable
[2021-07-28 16:05:26,468] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70808
[2021-07-28 16:06:05,286] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:06:07,375] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:06:08,584] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:07:44,549] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65335
[2021-07-28 16:07:44,702] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:07:46,473] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 86, in NumberOrganizeReport
    x1.append(x['Organize'])
TypeError: 'MiracleNumber' object is not subscriptable
[2021-07-28 16:07:46,474] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70809
[2021-07-28 16:08:19,008] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:08:20,991] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:08:24,567] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:08:26,932] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:08:28,082] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:08:30,278] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65335
[2021-07-28 16:08:30,436] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:08:31,817] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 86, in NumberOrganizeReport
    x1.append(x['Organize'])
TypeError: 'MiracleNumber' object is not subscriptable
[2021-07-28 16:08:31,818] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70808
[2021-07-28 16:09:33,925] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:09:36,174] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:09:41,025] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 83, in NumberOrganizeReport
    print(ORG[0:100].Org_num)
AttributeError: 'QuerySet' object has no attribute 'Org_num'
[2021-07-28 16:09:41,027] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70521
[2021-07-28 16:09:52,457] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 83, in NumberOrganizeReport
    print(ORG[0:100].Org_num)
AttributeError: 'QuerySet' object has no attribute 'Org_num'
[2021-07-28 16:09:52,459] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70521
[2021-07-28 16:10:01,769] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65335
[2021-07-28 16:10:01,913] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:10:03,397] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 83, in NumberOrganizeReport
    print(ORG[0:100].Org_num)
AttributeError: 'QuerySet' object has no attribute 'Org_num'
[2021-07-28 16:10:03,399] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70521
[2021-07-28 16:10:19,232] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:10:21,248] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:10:24,007] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 83, in NumberOrganizeReport
    print(ORG[:100].Org_num)
AttributeError: 'QuerySet' object has no attribute 'Org_num'
[2021-07-28 16:10:24,009] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70519
[2021-07-28 16:10:41,927] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:10:43,859] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:10:49,346] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:10:51,262] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65335
[2021-07-28 16:10:51,426] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:10:53,628] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 86, in NumberOrganizeReport
    x1.append(x['Organize'])
TypeError: 'MiracleNumber' object is not subscriptable
[2021-07-28 16:10:53,630] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 70803
[2021-07-28 16:15:19,773] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:15:21,968] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:15:48,257] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:15:50,232] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:15:59,349] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 21163
[2021-07-28 16:16:04,375] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 21163
[2021-07-28 16:16:39,503] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:16:41,547] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:16:53,278] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 21163
[2021-07-28 16:21:30,272] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:21:32,337] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:21:41,176] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 21163
[2021-07-28 16:22:23,016] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:22:25,043] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:22:28,077] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8290
[2021-07-28 16:23:11,039] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:23:12,981] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:24:11,847] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:24:14,075] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:24:27,736] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 82, in NumberOrganizeReport
    ORG = MiracleNumber.objects.filter('Organize' != '无').values('Organize').annotate(Org_num=Count('id')).values('Organize','Org_num').order_by('-Org_num')
  File "D:\Python39\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 941, in filter
    return self._filter_or_exclude(False, args, kwargs)
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 961, in _filter_or_exclude
    clone._filter_or_exclude_inplace(negate, args, kwargs)
  File "D:\Python39\lib\site-packages\django\db\models\query.py", line 968, in _filter_or_exclude_inplace
    self._query.add_q(Q(*args, **kwargs))
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 1391, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 1410, in _add_q
    child_clause, needed_inner = self.build_filter(
  File "D:\Python39\lib\site-packages\django\db\models\sql\query.py", line 1281, in build_filter
    arg, value = filter_expr
TypeError: cannot unpack non-iterable bool object
[2021-07-28 16:24:27,740] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 105099
[2021-07-28 16:24:50,066] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:24:52,011] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:26:12,603] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:26:15,040] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:26:17,531] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:26:20,652] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8243
[2021-07-28 16:27:17,631] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8243
[2021-07-28 16:27:18,676] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8243
[2021-07-28 16:27:20,062] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8243
[2021-07-28 16:27:21,671] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8243
[2021-07-28 16:27:22,341] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65335
[2021-07-28 16:27:22,502] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:27:25,432] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8243
[2021-07-28 16:27:38,960] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/?q=%E9%B1%BC%E9%B3%8D HTTP/1.1" 200 58588
[2021-07-28 16:27:39,122] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:27:50,510] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/?q=%E5%90%8C%E4%BB%81%E5%A0%82 HTTP/1.1" 200 55343
[2021-07-28 16:27:50,669] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:27:59,691] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/Miracle/miraclenumber/ajax HTTP/1.1" 200 62
[2021-07-28 16:28:01,033] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/?q=%E5%90%8C%E4%BB%81%E5%A0%82 HTTP/1.1" 200 49115
[2021-07-28 16:28:01,194] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:28:07,968] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:28:15,788] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65176
[2021-07-28 16:28:15,935] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:28:19,562] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8173
[2021-07-28 16:28:48,945] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/?q=%E9%87%91%E7%94%B0%E5%AE%A2%E6%9C%8D HTTP/1.1" 200 52707
[2021-07-28 16:28:49,093] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:28:57,071] [basehttp.py:161] [basehttp:log_message] [INFO]- "POST /admin/Miracle/miraclenumber/ajax HTTP/1.1" 200 62
[2021-07-28 16:28:58,345] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/?q=%E9%87%91%E7%94%B0%E5%AE%A2%E6%9C%8D HTTP/1.1" 200 49036
[2021-07-28 16:28:58,498] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:29:04,273] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/? HTTP/1.1" 200 65025
[2021-07-28 16:29:04,445] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:29:06,931] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8110
[2021-07-28 16:32:46,775] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:32:49,294] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:32:52,555] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8110
[2021-07-28 16:33:07,617] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:33:10,834] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:33:14,133] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8110
[2021-07-28 16:33:43,262] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:33:46,746] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:34:09,566] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:34:10,977] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65025
[2021-07-28 16:34:11,130] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:34:13,287] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7944
[2021-07-28 16:35:29,224] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:35:31,421] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:35:33,685] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:35:36,386] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65025
[2021-07-28 16:35:36,543] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:35:38,652] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7944
[2021-07-28 16:38:15,802] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:38:18,914] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:38:25,159] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7999
[2021-07-28 16:38:27,725] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7999
[2021-07-28 16:41:11,416] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:41:13,175] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65025
[2021-07-28 16:41:13,331] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:41:15,521] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7999
[2021-07-28 16:42:18,230] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:42:20,548] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:46:04,235] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:46:06,574] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:46:19,041] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:46:21,283] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65025
[2021-07-28 16:46:21,429] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:46:23,844] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7998
[2021-07-28 16:46:56,992] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:46:58,912] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:47:09,636] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:47:11,573] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:47:13,487] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7997
[2021-07-28 16:47:45,697] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:47:47,646] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:47:48,878] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:47:51,062] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7997
[2021-07-28 16:48:43,645] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:48:46,018] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:50:17,324] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:50:19,361] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:50:21,378] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65025
[2021-07-28 16:50:21,531] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:50:23,565] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8012
[2021-07-28 16:51:58,876] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:52:00,828] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:52:07,118] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7911
[2021-07-28 16:52:32,595] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:52:34,636] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:52:36,125] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:52:38,029] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65025
[2021-07-28 16:52:38,189] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:52:40,603] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7912
[2021-07-28 16:54:30,143] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:54:32,062] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:54:39,643] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7859
[2021-07-28 16:54:43,421] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7859
[2021-07-28 16:55:10,191] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:55:12,184] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:55:17,402] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7843
[2021-07-28 16:55:29,469] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:55:31,501] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:55:37,790] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7944
[2021-07-28 16:55:57,460] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:55:59,494] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:56:02,655] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7844
[2021-07-28 16:56:17,854] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:56:19,888] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:56:23,765] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 16:56:25,903] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65025
[2021-07-28 16:56:26,067] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 16:56:28,183] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7843
[2021-07-28 16:56:33,650] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7843
[2021-07-28 16:57:01,451] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:57:03,351] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:57:15,144] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:57:16,979] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:58:40,287] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:58:42,141] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:58:53,425] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 7944
[2021-07-28 16:59:33,253] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 16:59:35,250] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 16:59:39,098] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8118
[2021-07-28 17:03:31,987] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:03:33,976] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:03:42,830] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:03:44,839] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:03:52,358] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:03:54,446] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:04:02,168] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:04:04,224] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:04:14,643] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8118
[2021-07-28 17:04:23,983] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:04:25,876] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:04:27,143] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 17:04:29,201] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65025
[2021-07-28 17:04:29,359] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 17:04:31,829] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8118
[2021-07-28 17:05:49,655] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:05:51,593] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:05:55,222] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8149
[2021-07-28 17:06:02,934] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:06:05,202] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:06:08,546] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:06:10,591] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:06:12,649] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8150
[2021-07-28 17:06:26,544] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:06:28,507] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:06:30,503] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8151
[2021-07-28 17:10:23,866] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:10:25,816] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:10:31,008] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8151
[2021-07-28 17:10:40,624] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:10:42,551] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:10:44,983] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8151
[2021-07-28 17:12:55,626] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:12:57,539] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:13:05,621] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:13:07,533] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:13:20,410] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:13:22,370] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:13:24,416] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 86, in NumberOrganizeReport
    bar = Bar(InitOpts=opts.InitOpts(
TypeError: __init__() got an unexpected keyword argument 'InitOpts'
[2021-07-28 17:13:24,418] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 73416
[2021-07-28 17:14:16,893] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:14:18,775] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:14:28,106] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:14:29,652] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 17:14:31,508] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65025
[2021-07-28 17:14:31,658] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 17:14:33,157] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 88, in NumberOrganizeReport
    bar = Bar(
TypeError: __init__() got an unexpected keyword argument 'InitOpts'
[2021-07-28 17:14:33,158] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 73230
[2021-07-28 17:16:46,226] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:16:48,082] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:16:54,220] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 88, in NumberOrganizeReport
    bar = Bar(InitOpts=opts.InitOpts(animation_opts=opts.AnimationOpts(animation_delay=1000, animation_easing="elasticOut"),width='900px',height='500px')).add_xaxis(x1).set_global_opts(
TypeError: __init__() got an unexpected keyword argument 'InitOpts'
[2021-07-28 17:16:54,222] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 73635
[2021-07-28 17:17:41,960] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:17:43,920] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:17:47,749] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 88, in NumberOrganizeReport
    bar = Bar().add_xaxis(x1).set_global_opts(
TypeError: set_global_opts() got an unexpected keyword argument 'InitOpts'
[2021-07-28 17:17:47,751] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 73333
[2021-07-28 17:18:09,387] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:18:11,482] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:18:15,623] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8151
[2021-07-28 17:19:03,296] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:19:05,346] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:19:08,804] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:19:10,821] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:19:15,379] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:19:17,357] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:19:21,307] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8149
[2021-07-28 17:19:43,218] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8149
[2021-07-28 17:20:02,488] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:20:04,586] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:20:08,859] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8151
[2021-07-28 17:20:35,287] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:20:37,275] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:20:42,242] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8150
[2021-07-28 17:20:55,823] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:20:57,955] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:21:00,043] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8149
[2021-07-28 17:21:55,012] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:21:56,897] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:21:58,997] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8148
[2021-07-28 17:27:32,274] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:27:34,471] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:27:36,530] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 88, in NumberOrganizeReport
    bar = Bar(init_opts=opts.InitOpts(height='900px',width="1024")).add_xaxis(x1).set_global_opts(
TypeError: set_global_opts() got an unexpected keyword argument 'pos_left'
[2021-07-28 17:27:36,531] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 73428
[2021-07-28 17:28:26,892] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:28:28,943] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:28:49,476] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:28:51,406] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:28:54,016] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8175
[2021-07-28 17:29:07,366] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:29:09,517] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:29:13,092] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8175
[2021-07-28 17:29:22,377] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65025
[2021-07-28 17:29:22,521] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 17:30:18,243] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:30:20,255] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:30:23,034] [log.py:224] [log:log_response] [ERROR]- Internal Server Error: /crm/NumberOrganizeReport/
Traceback (most recent call last):
  File "D:\Python39\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python39\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "E:\djangoProject\crm\views.py", line 98, in NumberOrganizeReport
    label_opts=opts.LabelOpts(position="right",pos_left='15%'))
TypeError: __init__() got an unexpected keyword argument 'pos_left'
[2021-07-28 17:30:23,036] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 500 74822
[2021-07-28 17:31:18,566] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:31:20,522] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:54:50,344] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:54:52,361] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 17:54:57,048] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8150
[2021-07-28 17:57:41,688] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 17:57:43,903] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 18:03:17,902] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 18:03:19,823] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 18:03:35,764] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 18:03:37,785] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 18:04:03,126] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 18:04:05,153] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 18:04:08,488] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8251
[2021-07-28 18:04:26,140] [autoreload.py:250] [autoreload:trigger_reload] [INFO]- E:\djangoProject\crm\views.py changed, reloading.
[2021-07-28 18:04:28,117] [autoreload.py:636] [autoreload:run_with_reloader] [INFO]- Watching for file changes with StatReloader
[2021-07-28 18:04:30,293] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/ HTTP/1.1" 200 23177
[2021-07-28 18:04:32,286] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miraclenumber/ HTTP/1.1" 200 65025
[2021-07-28 18:04:32,438] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 18:04:34,714] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8251
[2021-07-28 18:11:29,633] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8251
[2021-07-28 18:11:34,714] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8251
[2021-07-28 18:11:36,802] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8251
[2021-07-28 18:11:40,718] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 5957
[2021-07-28 18:13:45,481] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberReport/ HTTP/1.1" 200 5957
[2021-07-28 18:14:10,216] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /crm/NumberOrganizeReport/ HTTP/1.1" 200 8251
[2021-07-28 18:15:16,303] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/tasks/task/ HTTP/1.1" 200 61119
[2021-07-28 18:15:16,450] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 18:16:49,732] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/Miracle/miracleorders/ HTTP/1.1" 200 49907
[2021-07-28 18:16:49,889] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 18:17:05,805] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/oblist/ HTTP/1.1" 200 414648
[2021-07-28 18:17:05,975] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 18:17:11,993] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/organization/ HTTP/1.1" 200 104844
[2021-07-28 18:17:12,155] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 18:17:14,325] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacts/ HTTP/1.1" 200 59453
[2021-07-28 18:17:14,483] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
[2021-07-28 18:17:17,327] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/crm/contacthistory/ HTTP/1.1" 200 55547
[2021-07-28 18:17:17,476] [basehttp.py:161] [basehttp:log_message] [INFO]- "GET /admin/jsi18n/ HTTP/1.1" 200 8398
